### PR TITLE
Make PySE run on multiple cores and fix a bug in the clipping algorithm.

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
I believe that merging the changes from the accelerated branch into master is a step to take now.
Let me explain why below.

The first thing to consider is that it does involve some changes, since it will not give the exact same output as the current `master` branch in all cases.
The reason is that it fixes the bug that no clipping was done at all when the source density was very high.
So it fixes a bug in the clipping algorithm for that case, making the clipping algorithm better in my opinion, but also slightly different, for all source densities.
That bug was fixed on the `Fix-no-clipping-when-source-density-is-high` branch and merged into accelerated quite some time ago.

Also some runtime warnings were fixed and `fudge_max_pix` and `maximum_pixel_method_variance` are computed only once per image, as it should be.

But the main work was to have PySE use multiple cores whenever possible without a major code overhaul. Those changes have zero effect on the output, but do make PySE faster.

All together PySE is now just over a factor two faster, but that is not fast enough within the goals of [PADRE](https://www.esciencecenter.nl/projects/the-petaflop-aartfaac-data-reduction-engine-padre/).

Therefore, I have proposed to start making use of [sep](https://github.com/kbarbary/sep) for online processing of AARTFAAC images . The more we use of sep, the closer we can get to SExtractor speed at the loss of some accuracy or features. 

But we want to keep that switch between offline and online processing.
This can be achieved by keeping separate branches within PySE. The user can always keep the option of slower, yet more accurate source extraction and measurement.

**None of sep is currently in this repo, to me it seems cleaner to first merge all of the current accelerations - as they have become part of the `accelerated` branch - into `master` before I embark on including any application of sep. Therefore, I submit this PR now.**

### CODE REVIEW

**Comment by AntoniaR** [comment]
Merged. Do you have any advice for applying this to the pyse version in the top repository?

**Comment by HannoSpreeuw** [comment]
Ah, you mean the pyse version in tkp? That is still Python 2, I presume. Better translate all of tkp to Python 3. Should be a couple of weeks work, I reckon. Algorithms like 2to3 do most of the job, but there will be some loose ends.

**Comment by AntoniaR** [comment]
Yes, it makes sense to apply your work there too!
So in theory, once we upgrade to Python 3, it should be straight forward? We have plans to start the upgrade this year with a software developer.

**Comment by HannoSpreeuw** [comment]
That is indeed what I expect. I can see that the pyse repo was created on May 24, 2017. So all the pyse code must have been part of the tkp repo before that.
Some time after this repo was created @gijzelaerr converted pyse from Python 2 to Python 3.
I did not change anything to the pyse external API, and I don't think anyone else did. So pyse should be able to communicate with the rest of tkp in the same way as before May 24, 2017.

**Comment by AntoniaR** [comment]
Excellent, thank you!

**Comment by HannoSpreeuw** [comment]
I do see [some changes](https://github.com/transientskp/tkp/commit/af8ff99d07df54cd0615fe9a0a04b8a9f0f92c93) to `extract.py` in `tkp/sourcefinder` that are more recent than May 24, 2017.
But that seems limited.

**Pull request merged**
