### PR TITLE
Fix values attribute override

### LINKED ISSUE #52: Implementation of `ParamSet` is inconsistent
### Description

Output from mypy
```
sourcefinder/extract.py:244: error: Cannot assign to a method  [method-assign]
sourcefinder/extract.py:244: error: Incompatible types in assignment (expression has type "dict[str, Uncertain]", variable has type "Callable[[], ValuesView[Any]]")  [assignment]
sourcefinder/extract.py:271: error: Value of type "Callable[[], ValuesView[Any]]" is not indexable  [index]
sourcefinder/extract.py:274: error: Unsupported right operand type for in ("Callable[[], ValuesView[Any]]")  [operator]
sourcefinder/extract.py:276: error: Unsupported target for indexed assignment ("Callable[[], ValuesView[Any]]")  [index]
sourcefinder/extract.py:278: error: Value of type "Callable[[], ValuesView[Any]]" is not indexable  [index]
sourcefinder/extract.py:279: error: Unsupported right operand type for in ("Callable[[], ValuesView[Any]]")  [operator]
sourcefinder/extract.py:280: error: Value of type "Callable[[], ValuesView[Any]]" is not indexable  [index]
sourcefinder/extract.py:295: error: "Callable[[], ValuesView[Any]]" has no attribute "keys"  [attr-defined]
```

The implementation is inconsistent.  While it inherits from `collections.abc.MutableMapping`, it doesn't respect the [mapping API](https://docs.python.org/3/glossary.html#term-mapping)

Problem is here (the first error above):
https://github.com/transientskp/pyse/blob/1de96f08469410abccd9e7a973f89d963faa4c2a/sourcefinder/extract.py#L244-L255

For example, in the line mentioned in the error above, it should not be overriding the `values()` method.  AFAIU, the implementation stores it's data as a regular `dict` in `ParamSet.values`, and all downstream use looks like this: `instance.values.<dict_method call>` instead of `instance.<dict_method_call>`.

### Resolution

1. Either `MutableMapping` should be removed.

   ```diff
   @@ -220,7 +220,7 @@ class Island(object):
            return measurement, gauss_residual
    
    
   -class ParamSet(MutableMapping):
   +class ParamSet:
        """
        All the source fitting methods should go to produce a ParamSet, which
        gives all the information necessary to make a Detection.
   ```

2. Or the implementation should be fixed to reflect the Python mapping API.

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
Should fix #52 

All 105 unit tests pass (1 skipped).

@suvayu Pls let me know if mypy thinks this is sufficient.

### CODE REVIEW

**Comment by HannoSpreeuw** [comment]
I see that some mypy type-checks, as included in our updated CI, have failed.
Those have nothing to do with this PR.
So these problems must have been present before.

I should be running mypy myself I guess.
How can I run exactly these mypy tests within PyCharm or from bash?

**Comment by suvayu** [comment]
I'll comment on the other points later.

> How can I run exactly these mypy tests within PyCharm or from bash?

`hatch run lint:mypy` in the terminal.  To run inside PyCharm, I don't know exactly, but there should be an option under linting/type checker.

**Comment by HannoSpreeuw** [comment]
Thanks, `hatch run lint:mypy` works and shows errors (and notes).

**Review by suvayu — APPROVED** [review]

**Comment by suvayu** [comment]
> All 105 unit tests pass (1 skipped).

The single skip is because of the dependency on the large dataset.  It only runs if you put the dataset there manually.  I added this test to fix the issue reported by Timo.  I'll make it mandatory after we find a solution for the large dataset issue.  I've an idea of what we could do, haven't investigated yet.

> I see that some mypy type-checks, as included in our updated CI, have failed.

I expect that step to fail until all the issues I opened recently are resolved (I think there might be some others where I did not file an issue because the resolution wasn't clear to me).

**Pull request merged**
