### PR TITLE
Reimplement dataaccessor

### LINKED ISSUE #53: Reimplement `DataAccessor` for easier testing & validation
From Mypy:
```
sourcefinder/accessors/dataaccessor.py:90: error: "DataAccessor" has no attribute "tau_time"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:91: error: "DataAccessor" has no attribute "freq_eff"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:92: error: "DataAccessor" has no attribute "freq_bw"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:93: error: "DataAccessor" has no attribute "taustart_ts"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:94: error: "DataAccessor" has no attribute "url"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:95: error: "DataAccessor" has no attribute "beam"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:96: error: "DataAccessor" has no attribute "beam"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:97: error: "DataAccessor" has no attribute "beam"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:98: error: "DataAccessor" has no attribute "centre_ra"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:99: error: "DataAccessor" has no attribute "centre_decl"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:100: error: "DataAccessor" has no attribute "pixelsize"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:101: error: "DataAccessor" has no attribute "pixelsize"  [attr-defined]
sourcefinder/accessors/dataaccessor.py:112: error: "DataAccessor" has no attribute "wcs"  [attr-defined]
```

This is because the base class uses a custom `metaclass`, and the base class doesn't really have these defined, but some methods use them (e.g. `extract_metadata`).

This kind of enforcement of API behaviour is much more cleanly achieved by using either of the following,
- [`NamedTuple`](https://docs.python.org/3/library/collections.html#namedtuple-factory-function-for-tuples-with-named-fields),
- [`dataclass`es](https://docs.python.org/3/library/dataclasses.html#module-dataclasses), or
- [`attrs`](https://www.attrs.org/en/stable/).

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
Following @suvayu on replacing DataAccessor by a dataclass.
DataAccessor was inheriting from RequiredAttributesMetaclass.
This way of enforcing required attributes seems too heavy machinery and the dataclass is a a lightweight solution.

Should also fix #53

### CODE REVIEW

**Comment by HannoSpreeuw** [comment]
Probably some loose ends although all unit tests pass, since `hatch run lint:mypy` yields

```
sourcefinder/utility/containers.py:55: error: Signatures of "__iadd__" and "__add__" are incompatible  [misc]
sourcefinder/accessors/lofarhdf5image.py:9: error: Missing positional arguments "beam", "centre_ra", "centre_decl", "data", "freq_bw", "freq_eff", "pixelsize", "tau_time", "taustart_ts", "url", "wcs" in call to "__init__" of "DataAccessor"  [call-arg]
sourcefinder/accessors/lofarhdf5image.py:62: error: "LofarHdf5Image" has no attribute "header"  [attr-defined]
sourcefinder/accessors/fitsimageblob.py:45: error: Signature of "_get_header" incompatible with supertype "FitsImage"  [override]
sourcefinder/accessors/fitsimageblob.py:45: note:      Superclass:
sourcefinder/accessors/fitsimageblob.py:45: note:          def _get_header(self, hdu_index: Any) -> Any
sourcefinder/accessors/fitsimageblob.py:45: note:      Subclass:
sourcefinder/accessors/fitsimageblob.py:45: note:          def _get_header(self, hdulist: Any, hdu_index: Any) -> Any
sourcefinder/accessors/fitsimageblob.py:48: error: Signature of "read_data" incompatible with supertype "FitsImage"  [override]
sourcefinder/accessors/fitsimageblob.py:48: note:      Superclass:
sourcefinder/accessors/fitsimageblob.py:48: note:          def read_data(self, hdu_index: Any, plane: Any) -> Any
sourcefinder/accessors/fitsimageblob.py:48: note:      Subclass:
sourcefinder/accessors/fitsimageblob.py:48: note:          def read_data(self, hdulist: Any, hdu_index: Any, plane: Any) -> Any
Found 5 errors in 3 files (checked 30 source files)
```

**Comment by HannoSpreeuw** [comment]
The line 
`sourcefinder/accessors/lofarhdf5image.py:61: error: "LofarHdf5Image" has no attribute "header"  [attr-defined]` from the `mypy` output has to do with

```
    def get_header(self):
        # Preserved for API compatibility.
        return self.header
```

Apparently not implemented yet.

Should not be solved as part of this PR.

**Comment by HannoSpreeuw** [comment]
The other `mypy` complaints have been taken care of through commit [d163f9b](https://github.com/transientskp/pyse/pull/66/commits/d163f9b46639d110feb2f148b2f4dc266f60092b).

**Review by suvayu — APPROVED** [review]
Hi @HannoSpreeuw, I'll approve these for now since the tests pass.  But I don't think this is completely there yet.  There are some inconsistencies that I would like to address.  I'll open a separate issue to collect everything I spotted, and we can address that in a separate PR.

Because of the above reason and #65, maybe #53 should still be open.

**Comment by HannoSpreeuw** [comment]
Allright.
So that means `DataAccessor` has been adequately reimplemented, but the design of its derived classes may need improvements.

**Pull request merged**
